[sourceNode]
node = "http://sentry-01.hosts.testnet.cudos.org:26657"

totalNodesChecked = 0

successfulNodes = {
}

unsuccessfulNodes = [
]

archiveNodes = [
]

successfulNodesGRPC = [
]

unsuccessfulNodesGRPC = [
]

successfulNodesAPI = [
]

unsuccessfulNodesAPI = [
]

