source_node = "https://rpc-composable-ia.cosmosia.notional.ventures:443"

total_nodes_checked = 79

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://217.76.49.110:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "STAVR-Service"
earliest_block = 5164001
rpc = "http://135.181.210.171:20307"
rpc_status = "successful"

[[nodes]]
name = "test"
earliest_block = 3640124
rpc = "https://rpc-composable-ia.cosmosia.notional.ventures:443"
rpc_status = "successful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://94.130.94.180:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://213.239.207.175:58657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://5.181.190.114:14657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://135.181.208.166:33657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://51.250.86.13:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "L0vd.com | RPC"
earliest_block = 1408001
rpc = "http://65.109.33.48:23657"
rpc_status = "successful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://65.109.116.23:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://65.108.106.156:27657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://136.243.104.103:10157"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://142.132.156.99:20207"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://65.109.117.102:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "CroutonDigital"
earliest_block = 1537001
rpc = "http://65.109.117.113:27957"
rpc_status = "successful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://65.108.236.140:25576"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://95.217.192.124:39557"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://65.108.232.168:41657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://185.225.191.100:36657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://5.9.104.181:16157"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://144.91.64.71:26657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://78.46.103.246:61957"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://144.76.97.251:49657"
rpc_status = "unsuccessful"

[[nodes]]
name = "default"
earliest_block = 0
rpc = "http://95.216.2.219:16657"
rpc_status = "unsuccessful"

[[nodes]]
name = "kjgno2uht93"
earliest_block = 2026379
rpc = "http://93.159.130.4:36657"
rpc_status = "successful"

successful_rpc_nodes = [
  "http://65.109.33.48:23657",
  "http://65.109.117.113:27957",
  "http://93.159.130.4:36657",
  "https://rpc-composable-ia.cosmosia.notional.ventures:443",
  "http://135.181.210.171:20307",
]

unsuccessful_rpc_nodes = [
  "http://144.76.97.251:49657",
  "http://65.108.236.140:25576",
  "http://95.217.192.124:39557",
  "http://65.108.232.168:41657",
  "http://185.225.191.100:36657",
  "http://5.9.104.181:16157",
  "http://144.91.64.71:26657",
  "http://78.46.103.246:61957",
  "http://95.216.2.219:16657",
  "http://5.181.190.114:14657",
  "http://217.76.49.110:26657",
  "http://",
  "http://94.130.94.180:26657",
  "http://213.239.207.175:58657",
  "http://65.108.106.156:27657",
  "http://135.181.208.166:33657",
  "http://51.250.86.13:26657",
  "http://65.109.116.23:26657",
  "http://136.243.104.103:10157",
  "http://142.132.156.99:20207",
  "http://65.109.117.102:26657",
]

