[sourceNode]
node = "http://localhost:26657"

totalNodesChecked = 4

successfulNodes = {
    "http://localhost:26657": "1",
}

unsuccessfulNodes = [
    "http://172.25.0.4:26657",
    "http://172.25.0.3:26657",
    "http://172.25.0.5:26657",
]

archiveNodes = [
    "http://localhost:26657",
]

successfulNodesAPI = [
    "http://localhost:1317",
]

unsuccessfulNodesAPI = [
    "http://172.25.0.4:1317",
    "http://172.25.0.3:1317",
    "http://172.25.0.5:1317",
]

