[sourceNode]
node = "http://localhost:26657"

totalNodesChecked = 4

successfulNodes = {
    "http://localhost:26657": "1",
}

unsuccessfulNodes = [
    "http://172.26.0.4:26657",
    "http://172.26.0.2:26657",
    "http://172.26.0.5:26657",
]

archiveNodes = [
    "http://localhost:26657",
]

successfulNodesGRPC = [
]

unsuccessfulNodesGRPC = [
    "localhost:26657",
    "172.26.0.4:26657",
    "172.26.0.2:26657",
    "172.26.0.5:26657",
]

